#!/bin/bash


export __application="$HOME/application"
export __archive_root="$HOME/__archive"
export __archive="$__archive_root/archive"
export __basis="$__archive_root/basis"
export __sensitive="$__archive_root/sensitive"
export __config="$HOME/__config"
export __distro=$(<"$__config/distro.txt")
export __distro_storage="$__archive/storage-freebsd/$__distro"

PATH="$__archive/tool-freebsd/bin:$PATH"
PATH="$__archive/tool-freebsd/build_bin:$PATH"
PATH="$__archive/tool-freebsd/scripts:$PATH"

export TIME_NAME="time-freebsd"



# "strategic micro update"
svn update "$__archive/platform-freebsd"
svn update "$__archive/storage-freebsd"
svn update "$__archive/tool-freebsd"

sleep 1s


watch_build &



