#!/bin/bash

if [ ! -d "~/__config" ]; then

	mkdir -p "~/__config"

fi


if [ ! -f "~/__config/__distro.h" ]; then

	echo "#define MANJARO_LINUX 1" > ~/__config/__distro.h
	
fi

if [ ! -f "~/__config/distro.txt" ]; then

	printf %s "manjaro" > ~/__config/distro.txt
	
fi

if [ ! -f "~/__config/name.txt" ]; then

	printf %s "Manjaro" > ~/__config/name.txt
	
fi





